- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Copy NGINX reverse proxy config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/yii2
  notify: reload nginx

- name: Enable config
  file:
    src: /etc/nginx/sites-available/yii2
    dest: /etc/nginx/sites-enabled/yii2
    state: link
    force: yes

- name: Remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure NGINX is started
  service:
    name: nginx
    state: started
    enabled: yes

handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
